[package]
name = "f4jumble"
description = "Implementation of Zcash's F4Jumble algorithm"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
    "Daira Hopwood <daira@electriccoin.co>",
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
blake2b_simd = "0.5"
const_format = "0.2.21"

[dev-dependencies]
proptest = "1"

[features]
default = ["std"]
std = []
