[package]
name = "equihash"
description = "The Equihash Proof-of-Work function"
version = "0.2.0"
authors = ["Jack Grigg <jack@z.cash>"]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
blake2b_simd = "1"
byteorder = "1"

[lib]
bench = false
