[package]
name = "eip681"
description = "Parsing functions and data types for Ethereum EIP 681 Payment Request URIs"
version = "0.0.0"
authors = [
    "Schell Scivally <schell@electriccoin.co>"
]
homepage = "https://github.com/zcash/librustzcash"
edition.workspace = true
readme = "README.md"
rust-version.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
# - Error handling
snafu = "0.8.6"

# - Parsing and Encoding
base64.workspace = true
ens-normalize-rs = "0.1.1"
nom.workspace = true
percent-encoding.workspace = true

# - Test dependencies
proptest = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
proptest.workspace = true

[features]
## Exposes APIs that are useful for testing, such as `proptest` strategies.
test-dependencies = ["dep:proptest"]

[lints]
workspace = true
